import { Schema, model } from "mongoose";

const carSchema = new Schema(
  {
    host: {
      type: Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },

    brand: {
      type: String,
      required: true,
      trim: true,
    },

    model: {
      type: String,
      required: true,
      trim: true,
    },

    year: {
      type: Number,
      required: true,
      min: 1900,
      max: new Date().getFullYear() + 1,
    },

    type: {
      type: String,
      enum: [
        "HATCHBACK",
        "SEDAN",
        "SUV",
        "MUV",
        "COUPE",
        "CONVERTIBLE",
        "LUXURY",
      ],
      required: true,
    },

    transmission: {
      type: String,
      enum: ["MANUAL", "AUTOMATIC"],
      required: true,
    },

    fuelType: {
      type: String,
      enum: ["PETROL", "DIESEL", "ELECTRIC", "HYBRID"],
      required: true,
    },

    seats: {
      type: Number,
      required: true,
      min: 1,
      max: 20,
    },

    pricePerDay: {
      type: Number,
      required: true,
      min: 0,
    },

    location: {
      city: {
        type: String,
        required: true,
        trim: true,
      },

      state: {
        type: String,
        required: true,
        trim: true,
      },

      pincode: {
        type: String,
        trim: true,
      },
    },

    images: [
      {
        url: {
          type: String,
          required: true,
        },
        public_id: {
          type: String,
          required: true,
        },
      },
    ],

    description: {
      type: String,
      trim: true,
      maxlength: 1000,
    },

    features: [
      {
        type: String,
        trim: true,
      },
    ],

    registrationNumber: {
      type: String,
      required: true,
      unique: true,
      uppercase: true,
      trim: true,
    },

    status: {
      type: String,
      enum: ["AVAILABLE", "UNAVAILABLE", "PENDING", "REJECTED"],
      default: "PENDING",
    },

    isActive: {
      type: Boolean,
      default: true,
    },

    // -----------------------------------------------
    // AI / RAG: Embedding vector for semantic search
    // Generated by Google Gemini gemini-embedding-2 (3072 dims)
    // select: false ensures it is NEVER sent to clients
    // -----------------------------------------------
    embedding: {
      type: [Number],
      default: undefined,
      select: false,
    },
  },
  {
    timestamps: true,
  }
);

const Car = model("Car", carSchema);

export default Car;